
// Auto-generated by export-aws-config.js - DO NOT EDIT MANUALLY
// Generated: 2025-12-31T08:59:25.631Z
// Environment: dev

export const awsConfig = {
  "Auth": {
    "Cognito": {
      "userPoolId": "eu-north-1_SXM79SBSG",
      "userPoolClientId": "7f4ho24fdplv2eg0r8t7mfitm5",
      "identityPoolId": "eu-north-1:ad0d0ae4-d1ce-4c38-b3d1-122b167e3349"
    }
  },
  "API": {
    "GraphQL": {
      "endpoint": "https://3hfwllveibfbrcugias4ayrbx4.appsync-api.eu-north-1.amazonaws.com/graphql",
      "region": "eu-north-1",
      "defaultAuthMode": "userPool"
    }
  },
  "Storage": {
    "S3": {
      "region": "eu-north-1"
    }
  }
};
