// Auto-generated by export-aws-config.js - DO NOT EDIT MANUALLY
// Generated: 2026-01-04T22:03:19.585Z
// Environment: live
// Region: eu-north-1

export const awsConfig = {
  "Auth": {
    "Cognito": {
      "userPoolId": "eu-north-1_T4gMUV4KC",
      "userPoolClientId": "6gmppll8d9bfptd9pibejlqhkk",
      "identityPoolId": "eu-north-1:4dc9ba10-3754-48b9-910e-c18c15858375"
    }
  },
  "API": {
    "GraphQL": {
      "endpoint": "https://exeqhpjwv5b6xjzcevl4x3l5ay.appsync-api.eu-north-1.amazonaws.com/graphql",
      "region": "eu-north-1",
      "defaultAuthMode": "userPool"
    }
  },
  "Storage": {
    "S3": {
      "region": "eu-north-1"
    }
  }
};
